on:
  push:
    branches: [main]

name: Lint and Package
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Package
        run: |
          npm ci
          npm run all

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push origin HEAD:main
