on: workflow_dispatch
name: Test
jobs:
  test:
    name: Run local workflow dispatch
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Local Action
        uses: ./
        with:
          account: 304998364617
          region: eu-central-1
          aws-tool: codeartifact-pypi
          codeartifact-repository: dss
          codeartifact-domain: kraussmaffei
      - run: pip install kmhelper